In [5]:
import pandas

In [6]:
read_file = pandas.read_csv('data/survey_results_public.csv', index_col = 0)

In [7]:
read_file

,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,...,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,Other,...,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,NaN,...,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
4,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,NaN,...,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Other;Codecademy;edX,...,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89180,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Bootstrapping a business;Freelance/contr...,"Associate degree (A.A., A.S., etc.)",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,Udemy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89181,I agree,I am a developer by profession,18-24 years old,"Student, full-time;Employed, part-time","Hybrid (some remote, some in-person)",School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
89182,I agree,I code primarily as a hobby,Prefer not to say,I prefer not to say,NaN,NaN,Something else,Books / Physical media;Hackathons (virtual or ...,NaN,Codecademy;Coursera,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89183,I agree,I am a developer by profession,Under 18 years old,"Employed, part-time;Student, part-time","Hybrid (some remote, some in-person)",Hobby;School or academic work,"Secondary school (e.g. American high school, G...",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,Udemy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
89184,I agree,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,Codecademy;Pluralsight;Coursera,...,Never,1-2 times a week,1-2 times a week,60-120 minutes a day,30-60 minutes a day,DevOps function;Developer portal or other cent...,"Information Services, IT, Software Development...",Appropriate in length,Easy,NaN

In [8]:
read_file = pandas.read_table('data/survey_results_public.csv', delimiter = ',', skiprows = [1, 3, 4], index_col = "ResponseId")

In [9]:
read_file

,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,...,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,
2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,Other,...,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Other;Codecademy;edX,...,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0
6,I agree,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Hobby;Professional development or self-paced l...,Some college/university study without earning ...,Books / Physical media;Colleague;Online Course...,Formal documentation provided by the owner of ...,Other,...,1-2 times a week,1-2 times a week,3-5 times a week,30-60 minutes a day,15-30 minutes a day,DevOps function;Microservices;Observability to...,Other,Appropriate in length,Neither easy nor difficult,96828.0
7,I agree,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Profe...,Some college/university study without earning ...,Friend or family member;Online Courses or Cert...,NaN,Udemy,...,1-2 times a week,3-5 times a week,1-2 times a week,Less than 15 minutes a day,15-30 minutes a day,Microservices;Automated testing;Continuous int...,"Information Services, IT, Software Development...",Appropriate in length,Easy,135000.0
8,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Codecademy;edX,...,NaN,NaN,NaN,60-120 minutes a day,30-60 minutes a day,None of these,Financial Services,NaN,NaN,80000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89180,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Bootstrapping a business;Freelance/contr...,"Associate degree (A.A., A.S., etc.)",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,Udemy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89181,I agree,I am a developer by profession,18-24 years old,"Student, full-time;Employed, part-time","Hybrid (some remote, some in-person)",School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
89182,I agree,I code primarily as a hobby,Prefer not to say,I prefer not to say,NaN,NaN,Something else,Books / Physical media;Hackathons (virtual or ...,NaN,Codecademy;Coursera,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89183,I agree,I am a developer by profession,Under 18 years old,"Employed, part-time;Student, part-time","Hybrid (some remote, some in-person)",Hobby;School or academic work,"Secondary school (e.g. American high school, G...",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,Udemy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
89184,I agree,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,Codecademy;Pluralsight;Coursera,...,Never,1-2 times a week,1-2 times a week,60-120 minutes a day,30-60 minutes a day,DevOps function;Developer portal or other cent...,"Information Services, IT, Software Development...",Appropriate in length,Easy,NaN

In [10]:
read_file.shape

(89181, 83)

In [9]:
# read_file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89184 entries, 0 to 89183
Data columns (total 84 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ResponseId                           89184 non-null  int64
 1   Q120                                 89184 non-null  object
 2   MainBranch                           89184 non-null  object
 3   Age                                  89184 non-null  object
 4   Employment                           87898 non-null  object
 5   RemoteWork                           73810 non-null  object
 6   CodingActivities                     73764 non-null  object
 7   EdLevel                              87973 non-null  object
 8   LearnCode                            87663 non-null  object
 9   LearnCodeOnline                      70084 non-null  object
 10  LearnCodeCoursesCert                 37076 non-null  object
 11  YearsCode                            87435 non-null  object
 12  YearsCodePro                         66136 non-null  object
 13  DevType                              76872 non-null  object
 14  OrgSize                              65043 non-null  object
 15  PurchaseInfluence                    64964 non-null  object
 16  TechList                             60851 non-null  object
 17  BuyNewTool                           83009 non-null  object
 18  Country                              87973 non-null  object
 19  Currency                             65334 non-null  object
 20  CompTotal                            48225 non-null  float64
 21  LanguageHaveWorkedWith               87140 non-null  object
 22  LanguageWantToWorkWith               80709 non-null  object
 23  DatabaseHaveWorkedWith               73435 non-null  object
 24  DatabaseWantToWorkWith               60911 non-null  object
 25  PlatformHaveWorkedWith               63628 non-null  object
 26  PlatformWantToWorkWith               51308 non-null  object
 27  WebframeHaveWorkedWith               66938 non-null  object
 28  WebframeWantToWorkWith               56741 non-null  object
 29  MiscTechHaveWorkedWith               57019 non-null  object
 30  MiscTechWantToWorkWith               46848 non-null  object
 31  ToolsTechHaveWorkedWith              77884 non-null  object
 32  ToolsTechWantToWorkWith              68315 non-null  object
 33  NEWCollabToolsHaveWorkedWith         85864 non-null  object
 34  NEWCollabToolsWantToWorkWith         76649 non-null  object
 35  OpSysPersonal use                    86557 non-null  object
 36  OpSysProfessional use                78587 non-null  object
 37  OfficeStackAsyncHaveWorkedWith       69090 non-null  object
 38  OfficeStackAsyncWantToWorkWith       53743 non-null  object
 39  OfficeStackSyncHaveWorkedWith        83439 non-null  object
 40  OfficeStackSyncWantToWorkWith        69776 non-null  object
 41  AISearchHaveWorkedWith               56328 non-null  object
 42  AISearchWantToWorkWith               46150 non-null  object
 43  AIDevHaveWorkedWith                  25904 non-null  object
 44  AIDevWantToWorkWith                  19587 non-null  object
 45  NEWSOSites                           87973 non-null  object
 46  SOVisitFreq                          87140 non-null  object
 47  SOAccount                            87852 non-null  object
 48  SOPartFreq                           66061 non-null  object
 49  SOComm                               87692 non-null  object
 50  SOAI                                 47858 non-null  object
 51  AISelect                             87973 non-null  object
 52  AISent                               61501 non-null  object
 53  AIAcc                                38594 non-null  object
 54  AIBen                                61396 non-null  object
 55  AIToolInterested in Using            32783 non-null  object
 56  AIToolCurrently Using                36137 non-null  object
 57  AIToolNot interested in Using        21069 non-null  object
 58  AINextVery different                 12661 non-null  object
 59  AINextNeither different nor similar  6599 non-null   object
 60  AINextSomewhat similar               6238 non-null   object
 61  AINextVery similar                   2621 non-null   object
 62  AINextSomewhat different             23303 non-null  object
 63  TBranch                              65768 non-null  object
 64  ICorPM                               43668 non-null  object
 65  WorkExp                              43579 non-null  float64
 66  Knowledge_1                          42535 non-null  object
 67  Knowledge_2                          41670 non-null  object
 68  Knowledge_3                          41798 non-null  object
 69  Knowledge_4                          41684 non-null  object
 70  Knowledge_5                          41527 non-null  object
 71  Knowledge_6                          41520 non-null  object
 72  Knowledge_7                          41467 non-null  object
 73  Knowledge_8                          41404 non-null  object
 74  Frequency_1                          41916 non-null  object
 75  Frequency_2                          41925 non-null  object
 76  Frequency_3                          41054 non-null  object
 77  TimeSearching                        42778 non-null  object
 78  TimeAnswering                        42629 non-null  object
 79  ProfessionalTech                     41783 non-null  object
 80  Industry                             36774 non-null  object
 81  SurveyLength                         86485 non-null  object
 82  SurveyEase                           86554 non-null  object
 83  ConvertedCompYearly                  48019 non-null  float64
dtypes: float64(3), int64(1), object(80)
memory usage: 57.2+ MB

In [10]:
# pandas.set_option('display.max_columns', 84)

In [16]:
import pandas as pd

In [17]:
data = { 'student_id' : [1, 2, 3, 4],
         'student_name' : ['Kiruba', 'Mathew', 'Shiva', 'Sathiya']}

In [19]:
value = pd.DataFrame(data)

In [20]:
value

   student_id student_name
0           1       Kiruba
1           2       Mathew
2           3        Shiva
3           4      Sathiya

In [21]:
pd.__version__

'2.2.3'

In [22]:
print(value)

   student_id student_name
0           1       Kiruba
1           2       Mathew
2           3        Shiva
3           4      Sathiya

In [28]:
series = [1, 2, 3]

In [30]:
series

[1, 2, 3]

In [31]:
series_value = pd.Series(series)

In [32]:
series_value

0    1
1    2
2    3
dtype: int64

In [37]:
Employee = {'students_name' : ['Shiva', 'Ram', 'Mani', 'Ajay'],
            "Department" : ['EEE', 'IT', 'Civil', 'Civil']}

In [40]:
storage = pd.DataFrame(Employee, index = [1, 'Two', 3, 4.0])

In [41]:
storage

    students_name Department
1           Shiva        EEE
Two           Ram         IT
3            Mani      Civil
4.0          Ajay      Civil